name: Code Quality

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Run code quality checks
      run: |
        python tools/commands.py quality

    - name: Run strict type checking (advisory)
      run: |
        python tools/commands.py lint-strict || echo "Type checking found issues (expected for Home Assistant integrations)"
      continue-on-error: true
